# Generated by Django 4.2 on 2023-05-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_content_note_maestria_note_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='imagem',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
