# Generated by Django 4.2 on 2023-05-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_summoners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summoners',
        ),
        migrations.AddField(
            model_name='note',
            name='champ_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
